CREATE TABLE [dbo].[Barcodes]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Message] NVARCHAR(MAX) NOT NULL, 
    [Format] NVARCHAR(50) NOT NULL, 
    [DateScanned] DATETIME NOT NULL DEFAULT(GETDATE())
)
